import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

import MenuMobile from "@/components/menuMobile/MenuMobile";
import Providers from "@/utils/providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<Header />
					<div className="mt-[100px] lg:mt-[166px]">{children}</div>
					<Footer />
					<MenuMobile />
				</Providers>
			</body>
		</html>
	);
}
